# Build the java binaries and add it to the assets of a release based on the tag
name: build and release

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    name: build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: 'jdk+fx'
      - name: Build with Maven
        run: |
          mvn initialize && mvn clean compile && mvn package -DskipTests
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: version ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            */target/*-${{ github.ref_name }}-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
