# Build the docker image and push it to GitHub Packages

name: node publisher

on:
  workflow_dispatch:
    branches:
      - multi_currency_new_dev
      - dev
      - master

env:
  REGISTRY: ghcr.io
  ORGANIZATION: coti-io

jobs:
  build:
    strategy:
      matrix:
        include:
          - MODULE: fullnode
            PACKAGE_NAME: coti-fullnode
    name: Build and push ${{ matrix.PACKAGE_NAME }} image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ matrix.PACKAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=latest-{{branch}}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.PACKAGE_NAME }} to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: "MODULE=${{ matrix.MODULE }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
